In [1]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.neighbors import KNeighborsRegressor

In [2]:
df = pd.read_csv(r"C:\Users\crazy\Downloads\Housing.csv")

In [3]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [4]:
df['bathrooms'].unique()

array([2, 4, 1, 3])

In [5]:
df['stories'].unique()

array([3, 4, 2, 1])

In [6]:
df['bedrooms'].unique()

array([4, 3, 5, 2, 6, 1])

In [7]:
df['parking'].unique()

array([2, 3, 0, 1])

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [9]:
df[df.duplicated()]

Empty DataFrame
Columns: [price, area, bedrooms, bathrooms, stories, mainroad, guestroom, basement, hotwaterheating, airconditioning, parking, prefarea, furnishingstatus]
Index: []

In [10]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [11]:
for i in df.columns:
    print("*"*10,i,"*"*10)

********** price **********
********** area **********
********** bedrooms **********
********** bathrooms **********
********** stories **********
********** mainroad **********
********** guestroom **********
********** basement **********
********** hotwaterheating **********
********** airconditioning **********
********** parking **********
********** prefarea **********
********** furnishingstatus **********

In [12]:
for i in df.columns:
    print("*"*10, i, "*"*10)
    
    # Count NaN values
    nan_count = df[i].isna().sum()
    
    # Count empty strings
    empty_count = (df[i] == "").sum()
    
    print("NaN values:", nan_count)
    print("Empty strings:", empty_count)

********** price **********
NaN values: 0
Empty strings: 0
********** area **********
NaN values: 0
Empty strings: 0
********** bedrooms **********
NaN values: 0
Empty strings: 0
********** bathrooms **********
NaN values: 0
Empty strings: 0
********** stories **********
NaN values: 0
Empty strings: 0
********** mainroad **********
NaN values: 0
Empty strings: 0
********** guestroom **********
NaN values: 0
Empty strings: 0
********** basement **********
NaN values: 0
Empty strings: 0
********** hotwaterheating **********
NaN values: 0
Empty strings: 0
********** airconditioning **********
NaN values: 0
Empty strings: 0
********** parking **********
NaN values: 0
Empty strings: 0
********** prefarea **********
NaN values: 0
Empty strings: 0
********** furnishingstatus **********
NaN values: 0
Empty strings: 0

In [13]:
X = df.drop('price',axis=1)## Input Features

In [14]:
X

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...
540,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [15]:
y = df[['price']]

In [16]:
y ## Output Variable

        price
0    13300000
1    12250000
2    12250000
3    12215000
4    11410000
..        ...
540   1820000
541   1767150
542   1750000
543   1750000
544   1750000

[545 rows x 1 columns]

## Step - 2 : Split the data into train and test

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state=4)

In [18]:
X_train

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
219,7000,3,1,2,yes,no,yes,no,no,0,no,unfurnished
108,3240,4,1,3,yes,no,no,no,no,1,no,semi-furnished
63,6360,4,2,3,yes,no,no,no,yes,2,yes,furnished
495,4000,3,1,2,yes,no,no,no,no,1,no,unfurnished
490,4350,3,1,2,no,no,no,yes,no,1,no,unfurnished
...,...,...,...,...,...,...,...,...,...,...,...,...
456,2398,3,1,1,yes,no,no,no,no,0,yes,semi-furnished
360,4040,2,1,1,yes,no,no,no,no,0,no,semi-furnished
439,3930,2,1,1,no,no,no,no,no,0,no,unfurnished
174,3800,3,1,2,yes,yes,yes,no,no,1,yes,unfurnished
122,6254,4,2,1,yes,no,yes,no,no,1,yes,semi-furnished

In [19]:
X_test

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
489,3300,3,1,2,no,no,no,no,no,1,no,semi-furnished
302,2145,3,1,3,yes,no,no,no,no,1,yes,unfurnished
66,13200,2,1,1,yes,no,yes,yes,no,1,no,furnished
270,4500,3,2,3,yes,no,no,yes,no,1,no,furnished
515,3210,3,1,2,yes,no,yes,no,no,0,no,unfurnished
...,...,...,...,...,...,...,...,...,...,...,...,...
303,4500,3,1,1,yes,no,yes,no,no,0,no,furnished
103,6350,3,2,3,yes,yes,no,no,yes,0,no,furnished
6,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
128,5500,3,1,3,yes,yes,no,no,yes,1,no,furnished
139,6360,3,1,1,yes,yes,yes,no,yes,2,yes,furnished

In [20]:
y_train

       price
219  4795000
108  6107500
63   7035000
495  2730000
490  2835000
..       ...
456  3118850
360  3710000
439  3255000
174  5250000
122  5950000

[436 rows x 1 columns]

In [21]:
y_test

        price
489   2835000
302   4200000
66    6930000
270   4340000
515   2450000
..        ...
303   4200000
103   6195000
6    10150000
128   5873000
139   5740000

[109 rows x 1 columns]

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [23]:
cat_df = X_train.select_dtypes(include='object')

In [24]:
cat_df

,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus
219,yes,no,yes,no,no,no,unfurnished
108,yes,no,no,no,no,no,semi-furnished
63,yes,no,no,no,yes,yes,furnished
495,yes,no,no,no,no,no,unfurnished
490,no,no,no,yes,no,no,unfurnished
...,...,...,...,...,...,...,...
456,yes,no,no,no,no,yes,semi-furnished
360,yes,no,no,no,no,no,semi-furnished
439,no,no,no,no,no,no,unfurnished
174,yes,yes,yes,no,no,yes,unfurnished
122,yes,no,yes,no,no,yes,semi-furnished

In [25]:
num_df = X_train.select_dtypes(include='number')

In [26]:
num_df

     area  bedrooms  bathrooms  stories  parking
219  7000         3          1        2        0
108  3240         4          1        3        1
63   6360         4          2        3        2
495  4000         3          1        2        1
490  4350         3          1        2        1
..    ...       ...        ...      ...      ...
456  2398         3          1        1        0
360  4040         2          1        1        0
439  3930         2          1        1        0
174  3800         3          1        2        1
122  6254         4          2        1        1

[436 rows x 5 columns]

In [27]:
from sklearn.preprocessing import OneHotEncoder
OHE = OneHotEncoder(sparse_output=False).set_output(transform='pandas')
cat_df_trans = OHE.fit_transform(cat_df)

In [28]:
cat_df_trans

,mainroad_no,mainroad_yes,guestroom_no,guestroom_yes,basement_no,basement_yes,hotwaterheating_no,hotwaterheating_yes,airconditioning_no,airconditioning_yes,prefarea_no,prefarea_yes,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
219,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
108,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
63,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
495,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
490,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
360,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
439,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
174,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
122,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0

In [29]:
cat_df_trans.reset_index(inplace=True)

In [30]:
cat_df_trans.drop('index',axis=1)

,mainroad_no,mainroad_yes,guestroom_no,guestroom_yes,basement_no,basement_yes,hotwaterheating_no,hotwaterheating_yes,airconditioning_no,airconditioning_yes,prefarea_no,prefarea_yes,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
3,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
4,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
431,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
432,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
433,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
434,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
435,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0

In [31]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler().set_output(transform='pandas')
num_df_trans = scaler.fit_transform(num_df)

In [32]:
num_df_trans

         area  bedrooms  bathrooms   stories   parking
219  0.365517       0.4   0.000000  0.333333  0.000000
108  0.106207       0.6   0.000000  0.666667  0.333333
63   0.321379       0.6   0.333333  0.666667  0.666667
495  0.158621       0.4   0.000000  0.333333  0.333333
490  0.182759       0.4   0.000000  0.333333  0.333333
..        ...       ...        ...       ...       ...
456  0.048138       0.4   0.000000  0.000000  0.000000
360  0.161379       0.2   0.000000  0.000000  0.000000
439  0.153793       0.2   0.000000  0.000000  0.000000
174  0.144828       0.4   0.000000  0.333333  0.333333
122  0.314069       0.6   0.333333  0.000000  0.333333

[436 rows x 5 columns]

In [33]:
num_df_trans.reset_index(inplace = True)

In [34]:
num_df_trans.pop('index')

0      219
1      108
2       63
3      495
4      490
      ...
431    456
432    360
433    439
434    174
435    122
Name: index, Length: 436, dtype: int64

In [35]:
num_df_trans

         area  bedrooms  bathrooms   stories   parking
0    0.365517       0.4   0.000000  0.333333  0.000000
1    0.106207       0.6   0.000000  0.666667  0.333333
2    0.321379       0.6   0.333333  0.666667  0.666667
3    0.158621       0.4   0.000000  0.333333  0.333333
4    0.182759       0.4   0.000000  0.333333  0.333333
..        ...       ...        ...       ...       ...
431  0.048138       0.4   0.000000  0.000000  0.000000
432  0.161379       0.2   0.000000  0.000000  0.000000
433  0.153793       0.2   0.000000  0.000000  0.000000
434  0.144828       0.4   0.000000  0.333333  0.333333
435  0.314069       0.6   0.333333  0.000000  0.333333

[436 rows x 5 columns]

In [36]:
num_df_trans

         area  bedrooms  bathrooms   stories   parking
0    0.365517       0.4   0.000000  0.333333  0.000000
1    0.106207       0.6   0.000000  0.666667  0.333333
2    0.321379       0.6   0.333333  0.666667  0.666667
3    0.158621       0.4   0.000000  0.333333  0.333333
4    0.182759       0.4   0.000000  0.333333  0.333333
..        ...       ...        ...       ...       ...
431  0.048138       0.4   0.000000  0.000000  0.000000
432  0.161379       0.2   0.000000  0.000000  0.000000
433  0.153793       0.2   0.000000  0.000000  0.000000
434  0.144828       0.4   0.000000  0.333333  0.333333
435  0.314069       0.6   0.333333  0.000000  0.333333

[436 rows x 5 columns]

In [37]:
num_df

     area  bedrooms  bathrooms  stories  parking
219  7000         3          1        2        0
108  3240         4          1        3        1
63   6360         4          2        3        2
495  4000         3          1        2        1
490  4350         3          1        2        1
..    ...       ...        ...      ...      ...
456  2398         3          1        1        0
360  4040         2          1        1        0
439  3930         2          1        1        0
174  3800         3          1        2        1
122  6254         4          2        1        1

[436 rows x 5 columns]

In [38]:
X_train_trans=pd.concat([num_df_trans,cat_df_trans],axis=1)

In [39]:
X_train_trans

,area,bedrooms,bathrooms,stories,parking,index,mainroad_no,mainroad_yes,guestroom_no,guestroom_yes,...,basement_yes,hotwaterheating_no,hotwaterheating_yes,airconditioning_no,airconditioning_yes,prefarea_no,prefarea_yes,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,0.365517,0.4,0.000000,0.333333,0.000000,219,0.0,1.0,1.0,0.0,...,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.106207,0.6,0.000000,0.666667,0.333333,108,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.321379,0.6,0.333333,0.666667,0.666667,63,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
3,0.158621,0.4,0.000000,0.333333,0.333333,495,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
4,0.182759,0.4,0.000000,0.333333,0.333333,490,1.0,0.0,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
431,0.048138,0.4,0.000000,0.000000,0.000000,456,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
432,0.161379,0.2,0.000000,0.000000,0.000000,360,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
433,0.153793,0.2,0.000000,0.000000,0.000000,439,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
434,0.144828,0.4,0.000000,0.333333,0.333333,174,0.0,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
435,0.314069,0.6,0.333333,0.000000,0.333333,122,0.0,1.0,1.0,0.0,...,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0

In [40]:
X_train_trans.pop('index')

0      219
1      108
2       63
3      495
4      490
      ...
431    456
432    360
433    439
434    174
435    122
Name: index, Length: 436, dtype: int64

In [41]:
y_train

       price
219  4795000
108  6107500
63   7035000
495  2730000
490  2835000
..       ...
456  3118850
360  3710000
439  3255000
174  5250000
122  5950000

[436 rows x 1 columns]

In [42]:
y_train.reset_index(inplace=True)

In [43]:
y_train

     index    price
0      219  4795000
1      108  6107500
2       63  7035000
3      495  2730000
4      490  2835000
..     ...      ...
431    456  3118850
432    360  3710000
433    439  3255000
434    174  5250000
435    122  5950000

[436 rows x 2 columns]

In [44]:
y_train.pop('index')

0      219
1      108
2       63
3      495
4      490
      ...
431    456
432    360
433    439
434    174
435    122
Name: index, Length: 436, dtype: int64

In [45]:
y_train

       price
0    4795000
1    6107500
2    7035000
3    2730000
4    2835000
..       ...
431  3118850
432  3710000
433  3255000
434  5250000
435  5950000

[436 rows x 1 columns]

In [46]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor()
model.fit(X_train_trans,y_train)

KNeighborsRegressor()

In [47]:
from sklearn.linear_model import LinearRegression

model_1= LinearRegression()
model_1.fit(X_train_trans,y_train)

LinearRegression()

In [48]:
X_test

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
489,3300,3,1,2,no,no,no,no,no,1,no,semi-furnished
302,2145,3,1,3,yes,no,no,no,no,1,yes,unfurnished
66,13200,2,1,1,yes,no,yes,yes,no,1,no,furnished
270,4500,3,2,3,yes,no,no,yes,no,1,no,furnished
515,3210,3,1,2,yes,no,yes,no,no,0,no,unfurnished
...,...,...,...,...,...,...,...,...,...,...,...,...
303,4500,3,1,1,yes,no,yes,no,no,0,no,furnished
103,6350,3,2,3,yes,yes,no,no,yes,0,no,furnished
6,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
128,5500,3,1,3,yes,yes,no,no,yes,1,no,furnished
139,6360,3,1,1,yes,yes,yes,no,yes,2,yes,furnished

In [49]:
num_df = X_test.select_dtypes(include='number')

In [50]:
num_df

      area  bedrooms  bathrooms  stories  parking
489   3300         3          1        2        1
302   2145         3          1        3        1
66   13200         2          1        1        1
270   4500         3          2        3        1
515   3210         3          1        2        0
..     ...       ...        ...      ...      ...
303   4500         3          1        1        0
103   6350         3          2        3        0
6     8580         4          3        4        2
128   5500         3          1        3        1
139   6360         3          1        1        2

[109 rows x 5 columns]

In [51]:
num_df.reset_index(inplace=True)

In [52]:
num_df

     index   area  bedrooms  bathrooms  stories  parking
0      489   3300         3          1        2        1
1      302   2145         3          1        3        1
2       66  13200         2          1        1        1
3      270   4500         3          2        3        1
4      515   3210         3          1        2        0
..     ...    ...       ...        ...      ...      ...
104    303   4500         3          1        1        0
105    103   6350         3          2        3        0
106      6   8580         4          3        4        2
107    128   5500         3          1        3        1
108    139   6360         3          1        1        2

[109 rows x 6 columns]

In [53]:
num_df.pop('index')

0      489
1      302
2       66
3      270
4      515
      ...
104    303
105    103
106      6
107    128
108    139
Name: index, Length: 109, dtype: int64

In [54]:
cat_df = X_test.select_dtypes(include='object')

In [55]:
cat_df

,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus
489,no,no,no,no,no,no,semi-furnished
302,yes,no,no,no,no,yes,unfurnished
66,yes,no,yes,yes,no,no,furnished
270,yes,no,no,yes,no,no,furnished
515,yes,no,yes,no,no,no,unfurnished
...,...,...,...,...,...,...,...
303,yes,no,yes,no,no,no,furnished
103,yes,yes,no,no,yes,no,furnished
6,yes,no,no,no,yes,yes,semi-furnished
128,yes,yes,no,no,yes,no,furnished
139,yes,yes,yes,no,yes,yes,furnished

In [56]:
cat_df.reset_index(inplace=True)

In [57]:
num_df_trans = scaler.transform(num_df)

In [58]:
cat_df

,index,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus
0,489,no,no,no,no,no,no,semi-furnished
1,302,yes,no,no,no,no,yes,unfurnished
2,66,yes,no,yes,yes,no,no,furnished
3,270,yes,no,no,yes,no,no,furnished
4,515,yes,no,yes,no,no,no,unfurnished
...,...,...,...,...,...,...,...,...
104,303,yes,no,yes,no,no,no,furnished
105,103,yes,yes,no,no,yes,no,furnished
106,6,yes,no,no,no,yes,yes,semi-furnished
107,128,yes,yes,no,no,yes,no,furnished
108,139,yes,yes,yes,no,yes,yes,furnished

In [59]:
cat_df.pop('index')

0      489
1      302
2       66
3      270
4      515
      ...
104    303
105    103
106      6
107    128
108    139
Name: index, Length: 109, dtype: int64

In [60]:
num_df_trans

         area  bedrooms  bathrooms   stories   parking
0    0.110345       0.4   0.000000  0.333333  0.333333
1    0.030690       0.4   0.000000  0.666667  0.333333
2    0.793103       0.2   0.000000  0.000000  0.333333
3    0.193103       0.4   0.333333  0.666667  0.333333
4    0.104138       0.4   0.000000  0.333333  0.000000
..        ...       ...        ...       ...       ...
104  0.193103       0.4   0.000000  0.000000  0.000000
105  0.320690       0.4   0.333333  0.666667  0.000000
106  0.474483       0.6   0.666667  1.000000  0.666667
107  0.262069       0.4   0.000000  0.666667  0.333333
108  0.321379       0.4   0.000000  0.000000  0.666667

[109 rows x 5 columns]

In [61]:
cat_df_trans = OHE.transform(cat_df)

In [62]:
cat_df_trans

,mainroad_no,mainroad_yes,guestroom_no,guestroom_yes,basement_no,basement_yes,hotwaterheating_no,hotwaterheating_yes,airconditioning_no,airconditioning_yes,prefarea_no,prefarea_yes,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
2,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
3,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
4,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
105,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
106,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
107,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
108,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0

In [63]:
num_df_trans.reset_index(inplace=True)
#cat_df_trans.reset_index(inplace=True)

In [64]:
cat_df_trans.reset_index(inplace=True)

In [65]:
num_df_trans.pop('index')

0        0
1        1
2        2
3        3
4        4
      ...
104    104
105    105
106    106
107    107
108    108
Name: index, Length: 109, dtype: int64

In [66]:
cat_df_trans.pop('index')

0        0
1        1
2        2
3        3
4        4
      ...
104    104
105    105
106    106
107    107
108    108
Name: index, Length: 109, dtype: int64

In [67]:
X_test_trans = pd.concat([num_df_trans,cat_df_trans],axis=1)

In [68]:
X_test_trans

,area,bedrooms,bathrooms,stories,parking,mainroad_no,mainroad_yes,guestroom_no,guestroom_yes,basement_no,basement_yes,hotwaterheating_no,hotwaterheating_yes,airconditioning_no,airconditioning_yes,prefarea_no,prefarea_yes,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,0.110345,0.4,0.000000,0.333333,0.333333,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.030690,0.4,0.000000,0.666667,0.333333,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
2,0.793103,0.2,0.000000,0.000000,0.333333,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
3,0.193103,0.4,0.333333,0.666667,0.333333,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
4,0.104138,0.4,0.000000,0.333333,0.000000,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,0.193103,0.4,0.000000,0.000000,0.000000,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
105,0.320690,0.4,0.333333,0.666667,0.000000,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
106,0.474483,0.6,0.666667,1.000000,0.666667,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
107,0.262069,0.4,0.000000,0.666667,0.333333,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
108,0.321379,0.4,0.000000,0.000000,0.666667,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0

In [69]:
y_test

        price
489   2835000
302   4200000
66    6930000
270   4340000
515   2450000
..        ...
303   4200000
103   6195000
6    10150000
128   5873000
139   5740000

[109 rows x 1 columns]

In [70]:
y_test.reset_index(inplace=True)

In [71]:
y_test

     index     price
0      489   2835000
1      302   4200000
2       66   6930000
3      270   4340000
4      515   2450000
..     ...       ...
104    303   4200000
105    103   6195000
106      6  10150000
107    128   5873000
108    139   5740000

[109 rows x 2 columns]

In [72]:
y_test.pop('index')

0      489
1      302
2       66
3      270
4      515
      ...
104    303
105    103
106      6
107    128
108    139
Name: index, Length: 109, dtype: int64

In [73]:
y_test

        price
0     2835000
1     4200000
2     6930000
3     4340000
4     2450000
..        ...
104   4200000
105   6195000
106  10150000
107   5873000
108   5740000

[109 rows x 1 columns]

In [74]:
X_test_trans

,area,bedrooms,bathrooms,stories,parking,mainroad_no,mainroad_yes,guestroom_no,guestroom_yes,basement_no,basement_yes,hotwaterheating_no,hotwaterheating_yes,airconditioning_no,airconditioning_yes,prefarea_no,prefarea_yes,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,0.110345,0.4,0.000000,0.333333,0.333333,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.030690,0.4,0.000000,0.666667,0.333333,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
2,0.793103,0.2,0.000000,0.000000,0.333333,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
3,0.193103,0.4,0.333333,0.666667,0.333333,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
4,0.104138,0.4,0.000000,0.333333,0.000000,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,0.193103,0.4,0.000000,0.000000,0.000000,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
105,0.320690,0.4,0.333333,0.666667,0.000000,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
106,0.474483,0.6,0.666667,1.000000,0.666667,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
107,0.262069,0.4,0.000000,0.666667,0.333333,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
108,0.321379,0.4,0.000000,0.000000,0.666667,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0

In [75]:
y_pred = model_1.predict(X_test_trans)
y_pred

array([[3376560.77802495],
       [4149294.2012204 ],
       [7066187.41745714],
       [6444114.34515628],
       [3500392.52669153],
       [3924887.54328483],
       [3472410.00337386],
       [4985569.60680821],
       [4610405.23810855],
       [5362280.90263081],
       [5015810.38954555],
       [3423277.54968349],
       [5623056.6529213 ],
       [4991989.57448598],
       [3258146.83846697],
       [6580171.28000056],
       [4641234.46578652],
       [8277990.78143868],
       [3879230.31800653],
       [3555561.41865287],
       [4662146.31650128],
       [5622387.27684366],
       [5896898.63641375],
       [7162321.43369478],
       [4693821.01068236],
       [5171192.86212308],
       [4909159.15742463],
       [6419749.95801011],
       [6420684.11892777],
       [6086218.80280111],
       [4672435.56880433],
       [6809784.54096198],
       [5922562.22873552],
       [3859781.57319858],
       [7392115.39230318],
       [3149535.17287659],
       [4214752.60327417],
       [3746103.66465071],
       [4587346.01170178],
       [7649764.70898684],
       [2698959.48886455],
       [4781401.42952287],
       [7382713.13508166],
       [5575118.1052096 ],
       [3703192.43857855],
       [3045551.67447025],
       [7699530.63845758],
       [3579452.16090045],
       [2771057.41925664],
       [8444268.81207152],
       [3170739.88118297],
       [3025486.37285319],
       [7951582.7410468 ],
       [5375529.55706115],
       [4214208.52859806],
       [3976466.20293354],
       [5366028.64625815],
       [2964315.28841286],
       [4162661.16575821],
       [5012486.65394264],
       [3340078.12843474],
       [3376216.0345403 ],
       [4086046.79440915],
       [2969615.42660061],
       [3196064.48627378],
       [5028858.40191876],
       [3161819.23822753],
       [3796951.14912337],
       [6840708.5862357 ],
       [3053600.22930681],
       [2247955.6491911 ],
       [6336007.09936456],
       [6434756.49429113],
       [3775904.35535165],
       [3446895.9562393 ],
       [3965250.24607538],
       [2765481.30476697],
       [4710883.08941975],
       [5280585.37481972],
       [4465139.78297585],
       [4911853.67018889],
       [4223672.99201597],
       [7523865.35659286],
       [2647943.47291402],
       [4147456.48670182],
       [2218643.9080795 ],
       [4888049.37123644],
       [5553422.34332385],
       [4065044.40727316],
       [6396194.80442042],
       [3015056.14409876],
       [3377331.25649894],
       [4328392.26704599],
       [4494936.69206544],
       [3269610.09148684],
       [4722559.36155265],
       [4190115.17024591],
       [6347975.8235895 ],
       [5651723.98337052],
       [3607243.04150954],
       [2723981.86795433],
       [3199225.09303531],
       [3468243.3153853 ],
       [4314483.44125743],
       [3679128.68323702],
       [6727222.04084658],
       [9919980.47457205],
       [5813986.48314287],
       [6293957.81753854]])

In [76]:
y_pred = model.predict(X_test_trans)
y_pred

array([[3409000.],
       [5066600.],
       [5117000.],
       [6552000.],
       [3969000.],
       [3977400.],
       [3353000.],
       [3619000.],
       [4319000.],
       [4445000.],
       [4373600.],
       [3808000.],
       [5220600.],
       [4942000.],
       [3294200.],
       [4544400.],
       [4534600.],
       [7448000.],
       [3739400.],
       [3409000.],
       [3731000.],
       [5789000.],
       [5507600.],
       [5593000.],
       [5173000.],
       [4352600.],
       [4445000.],
       [7385000.],
       [5327000.],
       [4044600.],
       [6433000.],
       [5604900.],
       [4821600.],
       [5066600.],
       [6979000.],
       [3960600.],
       [3402000.],
       [3969000.],
       [4841200.],
       [4806200.],
       [2986200.],
       [5024600.],
       [4373600.],
       [5692400.],
       [3969000.],
       [3602200.],
       [5327000.],
       [3490200.],
       [3239600.],
       [5880000.],
       [3969000.],
       [3003000.],
       [7784000.],
       [4162200.],
       [4144000.],
       [4137000.],
       [4786600.],
       [2940000.],
       [5066600.],
       [5579000.],
       [2910600.],
       [2910600.],
       [4520600.],
       [3577000.],
       [3556000.],
       [5327000.],
       [3568600.],
       [2856000.],
       [5066600.],
       [4918200.],
       [3005800.],
       [7238000.],
       [7182000.],
       [3612000.],
       [3318000.],
       [4228770.],
       [3535000.],
       [4436600.],
       [6881000.],
       [4058600.],
       [4452000.],
       [4519200.],
       [8260000.],
       [3918600.],
       [5682600.],
       [2986200.],
       [4226600.],
       [7012600.],
       [3910200.],
       [5689600.],
       [3568600.],
       [5066600.],
       [4837000.],
       [3402000.],
       [3514000.],
       [4478600.],
       [4520600.],
       [7035000.],
       [5579000.],
       [3969000.],
       [3512600.],
       [2856000.],
       [3456600.],
       [5163200.],
       [3808000.],
       [6825000.],
       [7182000.],
       [6447000.],
       [6225800.]])

In [77]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.49426389705873686

In [162]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [163]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [195]:
import joblib
joblib.dump({'model':model,'cat_encod':OHE,'num_encod':scaler},'model_prod_files13.pkl')

['model_prod_files13.pkl']

In [196]:
import joblib

joblib.dump({
    'model': model_1,
    'cat_encod': OHE,
    'num_encod': scaler
},'house_price_model13.pkl')

['house_price_model13.pkl']

In [197]:
prod_files = joblib.load('model_prod_files13.pkl')

In [198]:
prod_files['model']

KNeighborsRegressor()

# Applying hyperparamter tunning

In [78]:
param_grid = {
    "n_neighbors": [3,5,7,9,11,15,20],
    "weights": ["uniform", "distance"],
    "metric": ["euclidean", "manhattan"],
    "p": [1,2,3]
}

In [82]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsRegressor

In [83]:
knn = KNeighborsRegressor()

In [84]:
grid_knn = GridSearchCV(
    estimator=knn,
    param_grid=param_grid,
    cv=5,
    scoring="r2",
    n_jobs=-1
)

In [86]:
grid_knn.fit(X_train_trans, y_train)

GridSearchCV(cv=5, estimator=KNeighborsRegressor(), n_jobs=-1,
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9, 11, 15, 20],
                         'p': [1, 2, 3], 'weights': ['uniform', 'distance']},
             scoring='r2')

In [87]:
X_test_trans

,area,bedrooms,bathrooms,stories,parking,mainroad_no,mainroad_yes,guestroom_no,guestroom_yes,basement_no,basement_yes,hotwaterheating_no,hotwaterheating_yes,airconditioning_no,airconditioning_yes,prefarea_no,prefarea_yes,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,0.110345,0.4,0.000000,0.333333,0.333333,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.030690,0.4,0.000000,0.666667,0.333333,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
2,0.793103,0.2,0.000000,0.000000,0.333333,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
3,0.193103,0.4,0.333333,0.666667,0.333333,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
4,0.104138,0.4,0.000000,0.333333,0.000000,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,0.193103,0.4,0.000000,0.000000,0.000000,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
105,0.320690,0.4,0.333333,0.666667,0.000000,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
106,0.474483,0.6,0.666667,1.000000,0.666667,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
107,0.262069,0.4,0.000000,0.666667,0.333333,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
108,0.321379,0.4,0.000000,0.000000,0.666667,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0

In [88]:
y_test

        price
0     2835000
1     4200000
2     6930000
3     4340000
4     2450000
..        ...
104   4200000
105   6195000
106  10150000
107   5873000
108   5740000

[109 rows x 1 columns]

In [89]:
grid_knn.best_params_

{'metric': 'manhattan', 'n_neighbors': 7, 'p': 1, 'weights': 'uniform'}

In [90]:
grid_knn.best_score_

np.float64(0.5073139565855497)

In [94]:
from sklearn.tree import DecisionTreeRegressor
DT = DecisionTreeRegressor()
DT.fit(X_train_trans,y_train)

DecisionTreeRegressor()

In [98]:
y_pred_1 = DT.predict(X_test_trans)

In [99]:
y_pred_1

array([ 5530000.,  2100000.,  9800000.,  5600000.,  5110000.,  2940000.,
        3605000.,  4200000.,  4340000.,  3500000.,  3500000.,  4900000.,
        8400000.,  6629000.,  1750000.,  6685000.,  3500000.,  7980000.,
        3710000.,  2940000.,  4193000.,  4760000.,  6160000., 12250000.,
        3430000.,  4620000.,  4200000.,  6615000.,  5215000.,  3773000.,
        4550000.,  6020000.,  9240000.,  2233000., 11410000.,  3150000.,
        3703000.,  3290000.,  4480000., 12250000.,  4270000.,  6230000.,
        6510000.,  6419000.,  5250000.,  2961000., 11410000.,  4515000.,
        3360000.,  7700000.,  3080000.,  2310000.,  9310000.,  4060000.,
        6475000.,  4515000.,  4060000.,  3220000.,  2233000.,  6419000.,
        2240000.,  2835000.,  4340000.,  3710000.,  4340000.,  4480000.,
        4270000.,  2730000.,  4690000.,  1820000.,  2135000.,  6405000.,
        5250000.,  3850000.,  3010000.,  4900000.,  3745000.,  3640000.,
        4473000.,  4270000.,  5110000.,  4403000.,  8400000.,  4270000.,
        4900000.,  3353000.,  5040000.,  5950000.,  4375000.,  7560000.,
        4270000.,  3115000.,  4690000.,  2940000.,  2660000.,  5040000.,
        4340000.,  7420000.,  8120000.,  3500000.,  3675000.,  2450000.,
        3885000.,  4690000.,  4270000.,  6650000., 10850000.,  5810000.,
        5110000.])

In [100]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred_1)

0.019690976587245057

In [101]:
from sklearn.linear_model import LinearRegression

LR = LinearRegression()

LR.fit(X_train_trans,y_train)

LinearRegression()

In [102]:
y_pred = LR.predict(X_test_trans)

In [103]:
from sklearn.metrics import r2_score

r2_score(y_test,y_pred)

0.6585429213347469

In [157]:
from sklearn.linear_model import Lasso

lasso = Lasso(alpha =10000)
    
lasso.fit(X_train_trans,y_train)

Lasso(alpha=10000)

In [158]:
y_pred = lasso.predict(X_test_trans)

In [159]:
from sklearn.metrics import r2_score

r2_score(y_test,y_pred)

0.6688577211438121

In [160]:
from sklearn.linear_model import ElasticNet

elastic = ElasticNet(alpha =1,l1_ratio = 0.5)
    
elastic.fit(X_train_trans,y_train)

ElasticNet(alpha=1)

In [161]:
y_pred = elastic.predict(X_test_trans)

In [162]:
from sklearn.metrics import r2_score

r2_score(y_test,y_pred)

0.427509138883166